language: ruby
cache:
- bundler
gemfile: travisGemfile
install:
- bundle install
before_script:
- chmod +x deploy.sh
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script: "./deploy.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - HTML_FOLDER="./output/"
  - secure: acvFodFjI4BODkev02kw7OFhpN/tIi3734Z4p2orcKejQoI5LqeH1B4w6TGRvNP3oNT5iFPaLVFbcCg5mwGeliIYkBO4pR7hieoVMLDVZrXSZM2TojvC/ySTY5h3wvADQAfOOmcolz6a9L2egyGQ+4X2sybSmUqE1hGcVhDmrtVVZJjF42S9q2wTfNlN9v600/ITijCvS/AXR93tftrs+PbF/ir9BdyBYaXUMVI+nfrpxr8wGcP10Cm9RkyvdkuRU+Ipy8xQ0vg+MP/uJlPKqTsEaG5OV0IIveYvECJMqfCaOjqfcI0gjtLLD88cw+8jtt/C1p4dWR9fPR/DCY/1CUnRT+BK+7yydCgYgS8TVCWJtmvR+DZYC1jQG/LV8n8Z000zvALVCUmphiYVvXhU6rorlioDHsLvIaP43J2FhZktefaL8d/hfdmwZNXIPcvsTo55htkn75fG6j9rDKAVBnJDXBw5YK2BxazsbMC1ItLlRD1/72vfDbHBBY94eHCyQMfhIOBCzVvM7hEFvtFKbnTOBHW9tDggrHNn8k4lPojnUIDiB3M5/OI8dyuAzavtqESD8oMOR/OQ7xpAWew0sTaeJP62H6CihEP+o9oJEjA+UKtsueEyHdFnNara1StUeLvrsYXCbK3X/1RDY4ENm16Tn0I5yPwNCWvhfrE8XCk=
branches:
  only:
  - master
  - source
notifications:
  email: false
